/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MDI_DrugProject_package;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sabryazim
 */
public class AddForm extends javax.swing.JFrame {

    /**
     * Creates new form AddForm
     */
    public AddForm() {
        initComponents();
                        try{  

            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();  
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/test","sabryazim","5516");  
            if(con == null){
                JOptionPane.showMessageDialog(null,"connected failed","failed",JOptionPane.WARNING_MESSAGE);
            }
            Statement stmt=con.createStatement();  
            ResultSet rs=stmt.executeQuery("select * from `drug`");
    
            ResultSetMetaData metadata = rs.getMetaData();
            Vector<String> columnNames = new Vector<>();
            int columnCount = metadata.getColumnCount();
            //System.out.println(columnCount);
            Vector<Vector<Object>> dataVector = new Vector<Vector<Object>>();
            for(int i=1 ;i <= columnCount;i++){
                columnNames.add(metadata.getColumnName(i));
            }     
            
            while(rs.next()){
             Vector<Object> obj = new Vector<Object>();
             for(int i =1;i<= columnCount;i++){
                 obj.add(rs.getObject(i));
             }
             dataVector.add(obj);
            }  
              DefaultTableModel model = new DefaultTableModel(dataVector,columnNames);
              jTable1.setModel(model);
            con.close();  
        }catch(Exception e){ 
            JOptionPane.showMessageDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        drugSearchF = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        drugname = new javax.swing.JTextField();
        drugScName = new javax.swing.JTextField();
        drugClassification = new javax.swing.JTextField();
        drugPrice = new javax.swing.JTextField();
        drugCompany = new javax.swing.JTextField();
        drugCompany2 = new javax.swing.JTextField();
        drugUnit = new javax.swing.JTextField();
        drugDate = new javax.swing.JTextField();
        drugLicense = new javax.swing.JTextField();
        drugNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add new Drug");
        setLocation(new java.awt.Point(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        drugSearchF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        drugSearchF.setToolTipText("enter drug name or sc name or price !!");
        drugSearchF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                drugSearchFKeyPressed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        drugname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        drugScName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        drugClassification.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        drugPrice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        drugCompany.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        drugCompany2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        drugUnit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        drugDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        drugLicense.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        drugNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Trade name : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Sc. name : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Classification");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Price");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("company");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Company2");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Unit");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Date");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("License");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("No#");

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setText("Add new drug");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drugSearchF, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drugname, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drugScName, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drugClassification, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drugPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drugCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drugCompany2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drugUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drugDate, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drugLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drugNo, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(drugSearchF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(drugname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(drugScName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(btnSearch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(drugClassification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(drugPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(drugCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drugCompany2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drugUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drugDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drugLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drugNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        new mainForm().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int x = jTable1.getSelectedRow();
        drugname.setText(jTable1.getModel().getValueAt(x, 1).toString());
        drugScName.setText(jTable1.getModel().getValueAt(x, 2).toString());
        drugClassification.setText(jTable1.getModel().getValueAt(x, 3).toString());
        drugPrice.setText(jTable1.getModel().getValueAt(x, 4).toString());
        drugCompany.setText(jTable1.getModel().getValueAt(x, 5).toString());
        drugCompany2.setText(jTable1.getModel().getValueAt(x, 6).toString());     
        drugUnit.setText(jTable1.getModel().getValueAt(x, 7).toString());
        drugDate.setText(jTable1.getModel().getValueAt(x, 8).toString());
        drugLicense.setText(jTable1.getModel().getValueAt(x, 9).toString());
        drugNo.setText(jTable1.getModel().getValueAt(x, 10).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void drugSearchFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_drugSearchFKeyPressed
        if(evt.getKeyCode() == 10){
            try{

                Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
                Connection con=DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/test","sabryazim","5516");
                if(con == null){
                    JOptionPane.showMessageDialog(null,"connected failed","failed",JOptionPane.WARNING_MESSAGE);
                }
                /*
                String sql = "select * from drug WHERE TradeName  REGEXP (?)";
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(sql); */
                String query = "select * from drug WHERE TradeName  REGEXP (?) or ScName REGEXP (?) or Price REGEXP (?)";
                PreparedStatement st = con.prepareStatement(query);
                st.setString(1,drugSearchF.getText());
                st.setString(2,drugSearchF.getText());
                st.setString(3, drugSearchF.getText());
                ResultSet rs = st.executeQuery();

                ResultSetMetaData metadata = rs.getMetaData();
                Vector<String> columnNames = new Vector<>();
                int columnCount = metadata.getColumnCount();
                //System.out.println(columnCount);
                Vector<Vector<Object>> dataVector = new Vector<Vector<Object>>();
                for(int i=1 ;i <= columnCount;i++){
                    columnNames.add(metadata.getColumnName(i));
                }

                while(rs.next()){
                    Vector<Object> obj = new Vector<Object>();
                    for(int i =1;i<= columnCount;i++){
                        obj.add(rs.getObject(i));
                    }
                    dataVector.add(obj);
                }
                DefaultTableModel model = new DefaultTableModel(dataVector,columnNames);
                jTable1.setModel(model);
                con.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_drugSearchFKeyPressed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try{

            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/test","sabryazim","5516");
            if(con == null){
                JOptionPane.showMessageDialog(null,"connected failed","failed",JOptionPane.WARNING_MESSAGE);
            }
            /*
            String sql = "select * from drug WHERE TradeName  REGEXP (?)";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql); */
            String query = "select * from drug WHERE TradeName  REGEXP (?) or ScName REGEXP (?)";
            PreparedStatement st = con.prepareStatement(query);
            st.setString(1,drugSearchF.getText());
            st.setString(2,drugSearchF.getText());
            ResultSet rs = st.executeQuery();

            ResultSetMetaData metadata = rs.getMetaData();
            Vector<String> columnNames = new Vector<>();
            int columnCount = metadata.getColumnCount();
            //System.out.println(columnCount);
            Vector<Vector<Object>> dataVector = new Vector<Vector<Object>>();
            for(int i=1 ;i <= columnCount;i++){
                columnNames.add(metadata.getColumnName(i));
            }

            while(rs.next()){
                Vector<Object> obj = new Vector<Object>();
                for(int i =1;i<= columnCount;i++){
                    obj.add(rs.getObject(i));
                }
                dataVector.add(obj);
            }
            DefaultTableModel model = new DefaultTableModel(dataVector,columnNames);
            jTable1.setModel(model);
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
                try{

            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/test","sabryazim","5516");
            if(con == null){
                JOptionPane.showMessageDialog(null,"connected failed","failed",JOptionPane.WARNING_MESSAGE);
            }
            /*
            String sql = "select * from drug WHERE TradeName  REGEXP (?)";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql); */
            String query = "INSERT INTO drug (TradeName, ScName, Classification,Price, Company, Company2, Unit, Date, License, No) VALUES (?,?,?,?,?,?,?,?,?,?);";
            PreparedStatement st = con.prepareStatement(query);
            st.setString(1,drugname.getText().isEmpty()? "": drugname.getText());
            st.setString(2,drugScName.getText().isEmpty() ? "": drugScName.getText() );
            st.setString(3,drugClassification.getText().isEmpty() ? "": drugClassification.getText());
            st.setDouble(4, drugPrice.getText().isEmpty() ? 0.0: Double.parseDouble(drugPrice.getText()) );
            st.setString(5,drugCompany.getText().isEmpty() ? "": drugCompany.getText());
            st.setString(6,drugCompany2.getText().isEmpty() ? "": drugCompany2.getText());
            st.setString(7,drugUnit.getText().isEmpty() ? "": drugUnit.getText());
            st.setString(8,drugDate.getText().isEmpty() ? "": drugDate.getText());
            st.setString(9,drugLicense.getText().isEmpty() ? "": drugLicense.getText());
            st.setLong(10, drugNo.getText().isEmpty() ? 0: Long.parseLong(drugNo.getText()));
            //ResultSet rs = st.executeQuery();
            int rowInserted = st.executeUpdate();
            if(rowInserted > 0 ){
                JOptionPane.showMessageDialog(null, "the drug added successfully","note",JOptionPane.WARNING_MESSAGE);
            }

//            ResultSetMetaData metadata = rs.getMetaData();
//            Vector<String> columnNames = new Vector<>();
//            int columnCount = metadata.getColumnCount();
//            //System.out.println(columnCount);
//            Vector<Vector<Object>> dataVector = new Vector<Vector<Object>>();
//            for(int i=1 ;i <= columnCount;i++){
//                columnNames.add(metadata.getColumnName(i));
//            }
//
//            while(rs.next()){
//                Vector<Object> obj = new Vector<Object>();
//                for(int i =1;i<= columnCount;i++){
//                    obj.add(rs.getObject(i));
//                }
//                dataVector.add(obj);
//            }
//            DefaultTableModel model = new DefaultTableModel(dataVector,columnNames);
//            jTable1.setModel(model);
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddForm().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnSearch;
    private javax.swing.JTextField drugClassification;
    private javax.swing.JTextField drugCompany;
    private javax.swing.JTextField drugCompany2;
    private javax.swing.JTextField drugDate;
    private javax.swing.JTextField drugLicense;
    private javax.swing.JTextField drugNo;
    private javax.swing.JTextField drugPrice;
    private javax.swing.JTextField drugScName;
    private javax.swing.JTextField drugSearchF;
    private javax.swing.JTextField drugUnit;
    private javax.swing.JTextField drugname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
